/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/add/index.vue')['default']
    Added: typeof import('./src/components/added/added.vue')['default']
    Insert: typeof import('./src/components/insert/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Update: typeof import('./src/components/update/update.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanFiled: typeof import('vant/es')['Filed']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
  }
}
